-- [[============================================================]]
-- 基本属性（默认状态）
TUNING.THERESALUNA_HEALTH = 150   -- 生命值
TUNING.THERESALUNA_HUNGER = 150   -- 饥饿值
TUNING.THERESALUNA_SANITY = 150   -- 理智值

TUNING.THERESALUNA_COMBAT_MOD = 1 -- 攻击倍数

-- TODO: 血印槽还得做
-- 血印槽
TUNING.THERESALUNA_SANGUINE_MAX = 200 -- 上限

-- TODO: 数值还得在做
-- 基本属性（变身状态）
TUNING.THERESALUNA_GROWNUP_HEALTH = 200   -- 生命值
TUNING.THERESALUNA_GROWNUP_HUNGER = 200   -- 饥饿值
TUNING.THERESALUNA_GROWNUP_SANITY = 200   -- 理智值

TUNING.THERESALUNA_GROWNUP_COMBAT_MOD = 2 -- 攻击倍数
